### ISSUE TITLE
[ENHANCEMENT] Vault -> OpenBao

### ISSUE THREAD

**Issue by firegrass** [Smana/cloud-native-ref#253]
### Summary

Hashicorp Vault licensing changed from MPL to BSL last year. A team has forked Vault and intends to release soon under the original MPL license under the name OpenBao.

### Motivation

Allows continued use of Vault-like service without being pinned to old versions.

### Detailed Explanation

As above

### Benefits

As above

### Possible Drawbacks

- Might take a little while for OpenBao to get stable.
- Project might not get off the ground

### Additional Context

We need to wait til OpenBao put out an initial release.

**Comment by Smana** [comment]
Hey @firegrass , that's is definetely something we want to do. However, based on Openbao's documentation, the installation process is not straightforward yet. Need to dig deeper.

**Comment by Smana** [comment]
A [pull request](https://github.com/Smana/cloud-native-ref/pull/563) is currently being validated. So far everything seems to work smoothly.
However the web UI is not included anymore in the binary, see [this discussion](https://github.com/orgs/openbao/discussions/371). We need to decide if this is mandatory or not.

**Comment by Smana** [comment]
Tracking the reintroduction of the UI here: https://github.com/openbao/openbao/issues/739

That said, I decided to do the switch as the UI is not a strong requirement. Opening another issue for reintroducing it in the future.
